sudo: required

language: node_js
node_js:
  - "node"

services:
  - mysql

env:
  global:
    - REGISTRY_USER=cainiaccombo
    - IMAGE_NAME=cainiaccombo/fiesta
    - version=$TRAVIS_COMMIT
  - PORT=3030 MYSQL_URI=mysql://root@localhost:3306/fiesta

cache:
  directories:
    - "server/node_modules"
    - "client/node_modules"

install:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS fiesta;"
  - cd server; npm ci; cd ../
  - cd client; npm ci; cd ../

script:
  - cd server; npm test; cd ../
  - cd client; npm test; cd ../

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script:
    - docker push "${IMAGE_NAME}:latest"
    - docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
