sudo: required

language: node_js
node_js:
  - "node"

services:
  - mysql

env:
  - PORT=3030 MYSQL_URI=mysql://root@localhost:3306/fiesta

cache:
  directories:
    - "server/node_modules"
    - "client/node_modules"

before_install:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS fiesta;"
  - cd server; npm ci; cd ../
  - cd client; npm ci; cd ../

script:
  - cd server; npm test; cd ../
  - cd client; npm test; cd ../
