version: "3"

services:
  db:
    build: ./docker/db
    ports:
      - "3306:3306"
  fiesta:
    build: .
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - SQL_URI=mysql://root:password@db/fiesta
      - PORT=80
      - NODE_ENV=production
    volumes:
      - .:/var/www/Fiesta
      - /var/www/Fiesta/node_modules
    links:
      - db:db
    depends_on:
      - db
